#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"common/syscall.h\"\n";

print ".global syscall\n";
print "syscall:\n";
print " addi a7, a0, 0\n";
print " addi a0, a1, 0\n";
print " addi a1, a2, 0\n";
print " addi a2, a3, 0\n";
print " addi a3, a4, 0\n";
print " addi a4, a5, 0\n";
print " ecall\n";
print " ret\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("info");
entry("getlast");
entry("setlast");
entry("seed");
entry("rand");
entry("thread_create");
entry("thread_join");
entry("thread_exit");
